import os
import uuid
from datetime import datetime
from typing import Dict, Any, Optional
from backend.services.base import BaseService
from backend.config import settings

class ReportService(BaseService):
    """
    Service to generate, retrieve, and manage medical reports
    for analyzed 3D CT Scans.
    """

    def generate_html_report(self, scan_id: str, analysis_data: Dict[str, Any], patient_email: str = "N/A") -> str:
        """
        Generates a clean, print-ready HTML report representing the CT scan analysis.
        """
        prediction = analysis_data.get("prediction", "Unknown")
        confidence = analysis_data.get("confidence", 0.0)
        risk_level = analysis_data.get("risk_level", "low")
        findings = analysis_data.get("findings", [])
        recommendations = analysis_data.get("recommendations", [])
        gradcam_base64 = analysis_data.get("gradcam_base64", "")
        base_image_base64 = analysis_data.get("base_image_base64", "")

        findings_html = "".join(f"<li>{f}</li>" for f in findings)
        recommendations_html = "".join(f"<li>{r}</li>" for r in recommendations)

        gradcam_img_tag = f'<img src="data:image/png;base64,{gradcam_base64}" alt="Grad-CAM Heatmap" class="report-image" />' if gradcam_base64 else '<p>No heatmap visualization available.</p>'
        base_img_tag = f'<img src="data:image/png;base64,{base_image_base64}" alt="Base CT Slice" class="report-image" />' if base_image_base64 else '<p>No base slice image available.</p>'

        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>MedAI CT Scan Analysis Report</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.5; padding: 30px; }}
        .header {{ border-bottom: 2px solid #2B6CB0; padding-bottom: 15px; margin-bottom: 30px; }}
        .header h1 {{ margin: 0; color: #2B6CB0; font-size: 26px; }}
        .meta-info {{ display: flex; justify-content: space-between; margin-bottom: 30px; background: #F7FAFC; padding: 15px; border-radius: 5px; }}
        .meta-col {{ flex: 1; font-size: 14px; }}
        .meta-col strong {{ color: #4A5568; }}
        .badge {{ display: inline-block; padding: 5px 10px; border-radius: 4px; font-weight: bold; text-transform: uppercase; font-size: 12px; }}
        .badge-high {{ background-color: #FED7D7; color: #9B2C2C; }}
        .badge-low {{ background-color: #C6F6D5; color: #22543D; }}
        .section-title {{ color: #2B6CB0; font-size: 18px; border-bottom: 1px solid #E2E8F0; padding-bottom: 5px; margin-top: 30px; margin-bottom: 15px; }}
        .images-container {{ display: flex; gap: 20px; margin-top: 20px; }}
        .image-box {{ flex: 1; text-align: center; background: #F7FAFC; padding: 10px; border: 1px solid #E2E8F0; border-radius: 5px; }}
        .report-image {{ max-width: 100%; height: auto; max-height: 250px; border-radius: 3px; }}
        .footer {{ margin-top: 50px; border-top: 1px solid #E2E8F0; padding-top: 15px; text-align: center; font-size: 12px; color: #718096; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>MedAI 3D CT Scan Analysis Report</h1>
        <p>AI-Powered Lung Nodule Detection & Classification</p>
    </div>

    <div class="meta-info">
        <div class="meta-col">
            <strong>Scan ID:</strong> {scan_id}<br>
            <strong>Patient Email:</strong> {patient_email}<br>
            <strong>Date Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
        <div class="meta-col" style="text-align: right;">
            <strong>Risk Classification:</strong> 
            <span class="badge badge-{risk_level}">{risk_level}</span><br>
            <strong>Model Confidence:</strong> {confidence * 100:.2f}%
        </div>
    </div>

    <div class="section-title">AI Assessment & Findings</div>
    <p><strong>Primary Prediction:</strong> The AI system classified this scan as <strong>{prediction}</strong> with a confidence level of <strong>{confidence * 100:.2f}%</strong>.</p>
    <ul>
        {findings_html}
    </ul>

    <div class="section-title">Recommendations</div>
    <ul>
        {recommendations_html}
    </ul>

    <div class="section-title">Visual Interpretability (Grad-CAM Heatmaps)</div>
    <p>Grad-CAM visualizations highlight regions of high model attention. Red/warm areas indicate features that influenced the classification output.</p>
    <div class="images-container">
        <div class="image-box">
            <h4>Representative Base Slice</h4>
            {base_img_tag}
        </div>
        <div class="image-box">
            <h4>Grad-CAM Attention Map</h4>
            {gradcam_img_tag}
        </div>
    </div>

    <div class="footer">
        <p><strong>Disclaimer:</strong> This report is generated by an artificial intelligence model and is intended for informational and research purposes only. It does NOT constitute a formal medical diagnosis. All findings must be reviewed and verified by a board-certified radiologist.</p>
        <p>MedAI 3D CT Scan System &copy; {datetime.now().year}</p>
    </div>
</body>
</html>
"""
        return html_content

    def save_report(self, scan_id: str, user_id: str, title: str, summary: str, html_content: str) -> Dict[str, Any]:
        """
        Saves the generated report to both local storage (as HTML) and records its metadata in the database.
        """
        report_id = str(uuid.uuid4())
        filename = f"report_{report_id}.html"
        file_path = os.path.join(settings.OUTPUT_FOLDER, filename)

        # Save HTML report file
        self.logger.info(f"Saving HTML report to: {file_path}")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        # In production, we'd upload it to Supabase Storage and get a public URL.
        # For now, we will store a relative URL or path.
        pdf_url = f"/api/reports/download/{report_id}"

        report_data = {
            "id": report_id,
            "scan_id": scan_id,
            "user_id": user_id,
            "title": title,
            "summary": summary,
            "pdf_url": pdf_url,
            "created_at": datetime.utcnow().isoformat()
        }

        # Save to database
        if self.supabase is not None:
            self.logger.info(f"Saving report metadata to database for report_id: {report_id}")
            self.supabase.table("reports").insert(report_data).execute()

        return report_data

    def get_report_by_id(self, report_id: str) -> Optional[Dict[str, Any]]:
        """
        Retrieves report metadata from the database.
        """
        if self.supabase is None:
            return None
        response = self.supabase.table("reports").select("*").eq("id", report_id).maybe_single().execute()
        return response.data if response else None
